---
abstract: 'Unified interface for virus scanning of files/directories'
author:
  - 'Dave O''Neill (dmo@roaringpenguin.com)'
build_requires:
  Test::Class: 0
  Test::Exception: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.72'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: File-VirusScan
no_index:
  directory:
    - inc
    - t
requires:
  Data::ResultSet: 0
  File::Temp: 0
  HTML::TokeParser: 0
  IO::Dir: 0
  IO::File: 0
  IO::Select: 0
  IO::Socket::INET: 0
  IO::Socket::UNIX: 0
  Scalar::Util: 0
version: 0.100_01
